# Modeling Functions

This section specifies the user-facing functions required to simulate the system of ordinary differential equations.

## create_model

The `create_model` function is used to create the C code based on the text file representation of the model. This function returns and object of class `azrmod`. Once you create a model you can print a summary of the model in R. Below is an example of printing the simple harmonic oscillator, which is part of the **AZRsim** package.

```
sho <- create_model(system.file("examples/sho.txt", package="AZRsim"))
sho
AZRmodel
========
Name:                       Harmonic Oscillator
Number States:              2
Number Parameters:          1
Number Variables:           0
Number Reactions:           0
Number Functions:           0
```

In this model, the system of differential equations involves two states ($y_1$ and $y_2$) and one parameter ($\theta$).

## simulate

Once you have created an `azrmod` object with `create_model` you can use the `simulate` generic to simulate the state variables over a specified number of time steps. Note that the `simulate` function requires an object of class `azrmod`, and will return an object of class `azrsim` and `data.frame`.

In the simple harmonic oscillator example above we have two states, so calling `simulate(sho, seq(1, 100, by=0.1))` will provide a simulation of these two states over the time sequence 1 to 100 at 0.1 intervals.

## plot

The `plot` generic can be called on an `azrsim` object and, by default, will construct a lattice plot of the first 9 parameters over time.

## shiny_plot

The `shiny_plot` function must be called on an `azsim` object and will launch a shiny app that will allow the user to interactively include/exclude any state variable estimated.
