# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filter_check_dosing_table <- function(dosingTable, inputs) {
    .Call(`_AZRsim_filter_check_dosing_table`, dosingTable, inputs)
}

result_binding <- function(simres_all, simres_piece) {
    .Call(`_AZRsim_result_binding`, simres_all, simres_piece)
}

