# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

interpcse <- function(x, y, xi, s1 = NA_real_, s2 = NA_real_) {
    .Call('AZRsim_interpcse', PACKAGE = 'AZRsim', x, y, xi, s1, s2)
}

